---
abstract: 'Lexical aliasing of namespaces'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  B::Hooks::OP::Check: 0.11
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
configure_requires:
  B::Hooks::OP::Check: 0.11
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: namespace-alias
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::EndOfScope: 0
  B::Hooks::OP::Check: 0.11
  Class::MOP: 0
  XSLoader: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
